### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by mrfroggg** [turettn/fastapi_offline#36]
![image](https://github.com/turettn/fastapi_offline/assets/35123233/7f22f215-18b2-4c93-923b-f62bae39f48a)
When accessing my /docs
Using FastAPI 0.100.1 and fastapi-offline 1.6.0

/redoc works well

**Comment by turettn** [comment]
I spun up a new virtual environment, and did a `pip install fastapi_offline uvicorn`, started a simple server with a hello world, and was able to get the docs page to come up without issue.  By default, this gave me fastapi_offline 1.6.0 and fastapi 0.101.0.

I downgraded fastapi to 0.100.1 to try and replicate your setup, and it still worked.

Could you please try two things for me:
* Check the version number on `openapi.json` and let me know what it is.  For example, on my test environment `curl http://localhost:8000/openapi.json | jq .openapi` returns `"3.1.0"`.
* Force a refresh of your browser cache - I'm wondering if it's still grabbing swaggerui v4 instead of v5.  For example, do a Ctrl-Shift-R or use a browser you've never opened swagger with before.

Sorry I don't have a better answer for you.  I'm going to be out-of-office next week, but if you try the two experiments above and report back, I can pick this up when I return.

**Comment by turettn** [comment]
Closing since I can't replicate this and the thread has gone stale.
