### ISSUE TITLE
1.6.1: all responses in swagger are "string" instead of real data

### ISSUE THREAD

**Issue by ilBEastli** [turettn/fastapi_offline#39]
And an example of the same part in different versions

1.6.1:
![fastapi-offline-161](https://github.com/turettn/fastapi_offline/assets/1046421/0ac67bc4-3e3c-4c29-979d-92540b5ea589)

1.6.0:
![fastapi-offline-160](https://github.com/turettn/fastapi_offline/assets/1046421/42a229d1-4614-43f1-9730-2e34ae7fe6f8)

**Comment by turettn** [comment]
Gah - I'm having trouble replicating this.  With fastapi-offline 1.6.1 installed, I did this:

```python
from fastapi_offline import FastAPIOffline
from pydantic import BaseModel

app = FastAPIOffline()

class HelloWorldResponse(BaseModel):
        message: str

@app.get("/")
async def root() -> HelloWorldResponse:
        return HelloWorldResponse(message="asdf")
```

In Swagger UI, this looked pretty much like I'd expect:

![image](https://github.com/turettn/fastapi_offline/assets/11249393/6dab830c-77ef-4d7e-a515-0617a33ddc75)

This honestly feels like a Swagger / FastAPI issue - the only thing I can think would cause this would be a bad release.  If that bad release is on the FastAPI side, users can fix that themselves (`pip install fastapi --upgrade`).  If it's on the Swagger side, I need to vendor a new version and cut a new release of the package. 

Could you please:
* Provide the underlying FastAPI version number
* Try running your app with FastAPI instead of FastAPI-Offline (e.g. getting the newest SwaggerUI from the internet), and see if the issue persists.  If it doesn't, that's a strong indicator that I need to vendor a new SwaggerUI version.
* If your app still doesn't work, post the response model that's causing the issues.

**Comment by turettn** [comment]
Closing as stale - please feel free to re-open if there's new info.

**Comment by ilBEastli** [comment]
My bad. After some digging I've found out the culprit in my code: incorrect schema_extra definition. I've missed the ["examples" section](https://fastapi.tiangolo.com/tutorial/schema-extra-example/#__tabbed_1_2).
Version 1.6.0 ignored this mistake and just rendered the default example based on the model. But starting from 1.6.1 it started raising some JS errors at the top of the swagger page for the same code:
![image](https://github.com/turettn/fastapi_offline/assets/1046421/b21107bc-0d39-4b53-840d-d943b9768d46)

The code to reproduce this behaviour:
```import uvicorn
from fastapi_offline import FastAPIOffline
from pydantic import BaseModel
class User(BaseModel):
    id: int
    name: str
    class Config:
        schema_extra = {
            # "examples": [
            #     {
                    "id": 1,
                    "name": "user1",
            #    }
            # ]
        }
app = FastAPIOffline()
@app.get("/", response_model=User)
def handler():
    return User(id=1, name="user1")
if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
```

Anyway, thanks and sorry for the inconvenience 🙂

**Comment by turettn** [comment]
Glad you figured it out!
