### ISSUE TITLE
RFE: Modify an existing FastAPI app 

### ISSUE THREAD

**Issue by jeromeroussin** [turettn/fastapi_offline#45]
Hey, great stuff. I sometimes have to deploy applications in semi-restricted networking environments and FastAPIOffline is very helpful, thanks!

I was wondering if FastAPIOffline could also support being passed in an existing FastAPI instance rather than generating a new one, maybe a FastAPIOffline.from_app(app) or some such. This would make integrating with distributed FastAPI apps a little easier I think (and by that I mean apps that are defined in a pypi module of some kind and therefore not easily modifiable). 

One could do something like:
```python
import Foo
from fastapi_offline import FastAPIOffline

app = FastAPIOffline.from_app(Foo.app)
```

If you'll only consider a PR I understand, let me know what you think of the idea if you can though. Thanks again,

Jerome

**Comment by turettn** [comment]
It's been a while since I've looked at this particular issue, and from what I remember the only way to accomplish this was to do a lot of weird copying (with mutation) of a bunch of FastAPI internals.  It seemed like opening that can of worms would strongly couple this package to a bunch of the internal (vs the public APIs) of the FastAPI package, and would likely incur a significant cost in terms of reliability & supportability.

I haven't looked at it in a while though, and I'm afraid I probably won't get a chance to do so in the near future.

If you can find a clean way to do it, I'll happily look at a PR.  Alternatively, I've seen people solve this problem via monkey-patching:

```python
# test.py
import fastapi
import fastapi_offline
fastapi.FastAPI = fastapi_offline.FastAPIOffline
from other_package import app
```

then run something like

```bash
uvicorn test:app
```

Sorry I can't be more help.  If you'd like to try to implement a `from_app` method, let me know and I'll leave the issue open.  Otherwise I'll close it out in a week or so as "not planned".

**Comment by jeromeroussin** [comment]
Thanks so much! I had eliminated the monkey-patching option thinking it would lead to an infinite loop, but lo and behold it works. The learning never stops. You may close this, and thanks again.
